apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
type: Opaque
stringData:
  secret-access-credentials: GCP_SM_CREDENTIALS
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
              namespace: default
        projectID: template-project-419601
        
