apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
type: Opaque
stringData:
  secret-access-credentials: |-
    {
      "type": "service_account",
      "project_id": "template-project-419601",
      "private_key_id": "318d054efc3aceb66784bdece394d371b57f6fcf",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCpfG7jnF9SotRb\n2cS2fMWAX0+VYtEfort5BuGZhGNMnlu3zXJIo4S+KDmTEFoRHqNCRUA0MCPyAm//\nARsxnO+Btp4DazMsAq1y+kqEsvOqbKDBwPx09f/DmdfAfRmgjamjH84e8MXN6sN0\nnQ8XgI08kJKUe7d47v16diwVQ0NwT5BC3+I52dzVIW5Xm15BVSLM9yUQwe/KcI8r\nziUiMYlEiG6Qdug8un6d7qGJ0t5JSwrRfaEKxGCyBF0EvFVFrrireeSgAcoYAaqn\noBf/7JyOHxtwrOB87Sf4fekqgWlUJ8H2FvWxqyTJb7Y8belkWay4rlLG+6qsr5xX\ns7p/nfgjAgMBAAECggEAJyK5hEtOY4l/2bm+R5kmDc90U/1eZpywB3FEVKuSNlX2\nvclt00IW28X0DXZgJcXaUuokuihHlJFlhQ+fVOR1FZGyiP2O8mGn5X3QCTY9N6Qf\ntr22Tdej+GmkvSjl6wHrIuSsNs7IDhVgjqPZoUao1kxX3Ht40S72TvnMkhhXES6d\nxPaUjf4ESLvPO8s2PJfufb3QKf2747gd6akJ5aRz8wqHvKHQevgvQpS5qyniLMNN\n2KqiS3w1gqznlLwcVQ0J9RcnlV1sQxFmZw4FjNLrwydTJSW855vcKBTANBHLldEP\n5yENFAvHQoFAkQVSuminYCZjEgWJ6jf/ojdp+jABmQKBgQDammchOiZMEzsbmPk3\npyfkVubVoOD4R9wUTDoLYdbfNzGSFa0Wt/Ckn7ReRVo8CzCP71BMH/5GCwIrfknr\nHe2HH7mxlWjg4M7uXyv6L1i7Y21X+JpA212ZCPoYOEb/7DO/CgzS7NMZKKo8IE5h\nTG3qTtamPUpHsR/x53Mi5b3HNwKBgQDGevoStq3tcrYPfZ124Aosnp/vN+LluRXd\naq9lCTVWCRoeAxf0YztBzDjfEmfLwxgeSDosD7HFNU35zsmvyBWoiRwhTc6gs9Q7\nIin6NTCnQn6i5X3kK+0ci8rt18mVWGD+TPBm7K9jtVVaIfprsePYmDK7keMfa+xW\nejcmP8t0dQKBgDLoTigAwLZqrBMrNq5tMO8OBceuJXXsViYr8kCAUme9FMAuaBao\nU1QjFP/3KqJdALwkQRDZSn/JRIIYcOJeH9id3MKsRrZH5CjC5RzoNcO9zdL0xAdi\njpN68bL+OBqVSR+uGXptSGPNgodqBpbGE7rDDV29XDUB3Kya98citWVVAoGBALz4\nhzHcBhrGFbsH8S0mP+mdmU6MWhY4My4djiLXMpXYkqoybdM7y0ZpJ1iT0Ik7FbJ3\nOBONWccWakhGbtZS3PQantLCntF4hb9LVsYncEw/TgzQDR16CQYdvrbWtdHgVHCq\nVlTYUmDPXBU1tpRkyTcGKX9WdfULrvfi4rEjGhWlAoGBAJRU0+5JC++Be1YvRLlc\neQ/3hT4Gw5PRez1mzzJmjJLpPhhyLsmWSKZpabcjRBLX5ZRbEeNZKE1VfWaL1am9\n4emdSIK9PAf+CLnfnz2KpCvVBwRNyyZH8RLtFyiseK0Q8FBtl/0PdAcaF1sOmulS\ntR6Wk+iwIV+Ps3buXXp0OK7E\n-----END PRIVATE KEY-----\n",
      "client_email": "github-action@template-project-419601.iam.gserviceaccount.com",
      "client_id": "117923952639601525485",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/github-action%40template-project-419601.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
              namespace: default
        projectID: template-project-419601
        
