name: Create Kubernetes Cluster and Install Argo

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    permissions:
      id-token: write
      contents: read

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Configure GCP credentials
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/${{secrets.PROJECT_NO}}/locations/global/workloadIdentityPools/${{secrets.POOL_NAME}}/providers/${{secrets.PROVIDERS_NAME}}'
        service_account: ${{secrets.SERVICE_ACCOUNT}}
        token_format: "access_token"
        create_credentials_file: true
        activate_credentials_file: true

    - name: Install Terraform
      id: install-terraform
      run: wget -O terraform.zip https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && sudo mv terraform /usr/local/bin
    - name: Apply Terraform
      id: apply-terraform
      run: sed -i "s/${{ secrets.PROJECT_ID }}/${{ secrets.PROJECT_ID }}/g" main.tf && terraform init && terraform apply -auto-approve -var="project_id=${{ secrets.PROJECT_ID  }}"
      
